from pynput.keyboard import Key

keyboard = \
    {
        # Main gauche
        '(': 'Sol#3',
        't': 'Mi3',
        'g': 'MiM3',
        'b': 'Mim3',
        "'": 'Do#3',
        'r': 'La3',
        'f': 'LaM3',
        'v': 'Lam3',
        '"': 'Fa#3',
        'e': 'Re3',
        'd': 'ReM3',
        'c': 'Rem3',
        'é': 'Si3',
        'z': 'Sol3',
        's': 'SolM3',
        'x': 'Solm3',
        '&': 'Mi3',
        'a': 'Do3',
        'q': 'DoM3',
        'w': 'Dom3',
        '²': 'La3',
        Key.tab: 'Fa3',
        Key.caps_lock: 'FaM3',
        '<': 'Fam3',

        # Main droite
        '-': 'Fa3',
        'y': 'Sol3',
        'è': 'Sol#3',
        'h': 'La3',
        'u': 'La#3',
        '_': 'Si3',
        'j': 'Do4',
        'i': 'Do#4',
        'ç': 'Re4',
        'k': 'Re#4',
        'o': 'Mi4',
        'à': 'Fa4',
        'l': 'Fa#4',
        'p': 'Sol4',
        ')': 'Sol#4',
        'm': 'La4',
        '^': 'La#4',
        '=': 'Si4',
        'ù': 'Do5',
        '$': 'Do#5',
        Key.backspace: 'Re5',
        Key.enter: 'Mi5'
    }
