from pynput.keyboard import Key

keyboard = \
    {
        'a': 'Mi2',
        'é': 'Fa2',
        'q': 'Fa#2',
        'z': 'Sol2',
        '"': 'Sol#2',
        's': 'La2',
        'e': 'La#2',
        "'": 'Si2',
        'd': 'Do3',
        'r': 'Do#3',
        '(': 'Re3',
        'f': 'Re#3',
        't': 'Mi3',
        '-': 'Fa3',
        'g': 'Fa#3',
        'y': 'Sol3',
        'è': 'Sol#3',
        'h': 'La3',
        'u': 'La#3',
        '_': 'Si3',
        'j': 'Do4',
        'i': 'Do#4',
        'ç': 'Re4',
        'k': 'Re#4',
        'o': 'Mi4',
        'à': 'Fa4',
        'l': 'Fa#4',
        'p': 'Sol4',
        ')': 'Sol#4',
        'm': 'La4',
        '^': 'La#4',
        '=': 'Si4',
        'ù': 'Do5',
        '$': 'Do#5',
        Key.backspace: 'Re5',
        Key.enter: 'Mi5'
    }
